#MySQL \uC14B\uD305
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/articles
    username: ${DB_USER}
    password: ${DB_PW}
  sql:
    init:
      mode: always
    # alwoys : \uB9E4\uBC88, embedded : \uB0B4\uC7A5 DB\uB9CC, never : \uBAA8\uB4E0 \uB3D9\uC791 \uC548\uD568.
  jpa:
    #spring.sql.init \uCD08\uAE30 \uC791\uC5C5 \uD560 \uB54C \uB370\uC774\uD130 \uC0DD\uC131\uC744 \uC5B8\uC81C \uD560\uAC70\uB0D0?
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true