#MySQL 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/articles
    username: ${DB_USER}
    password: ${DB_PW}
  sql:
    init:
      mode: never
    # alwoys : 항상, embedded : 내장메모지디비, never : 사용안함
  jpa:
    #spring.sql.init
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true